sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      language: lua
      install:
        - sudo apt install luarocks
        - sudo apt install busted
      script:
        - busted
    - os: osx
      osx_image: xcode10.2
      language: lua
      install:
        - brew install luarocks
        - brew install busted
      script:
        - busted
