sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      language: lua
      install:
        - sudo apt-get update && apt-get -y upgrade; apt-get install -y build-essential
        - sudo apt install luarocks
        - luarocks install busted
        - luarocks install luacov
      script:
        - busted
    - os: osx
      osx_image: xcode10.2
      language: lua
      install:
        - brew install luarocks
        - luarocks install busted
        - luarocks install luacov
      script:
        - busted
