sudo: required

matrix:
  include:
    - os: linux
      dist: xenial
      language: lua
      install:
        - sudo apt-get install -y build-essential
        - sudo apt install luarocks
        - sudo luarocks install busted
        - sudo luarocks install luacov
      script:
        - busted
    - os: osx
      osx_image: xcode10.2
      language: lua
      install:
        - brew install luarocks
        - luarocks install busted
        - luarocks install luacov
      script:
        - busted
